Create database Walmart;
use Walmart;

select * from walmart;
select count(*) from walmart;
select payment_method,
    count(*)
 from Walmart
 group by payment_method;
 
 select count(distinct branch)
 from Walmart;
 select max(quantity) from walmart;
  select min(quantity) from walmart;
  
  
-- Business problems
--  Q.1 Find diff payment method, no of transactions and no. of quantity sold
  select 
	payment_method,
    count(*) as no_of_transactions,
    sum(quantity) as no_quantity_sold
 from Walmart
 group by payment_method;

 -- Q.2 find the highest rated category in each branch, category, avg rating
SELECT * 
from( 
select
    branch,
    category,
    AVG(rating) AS avg_rating,
    RANK() OVER (PARTITION BY branch ORDER BY AVG(rating) DESC) AS rnk
FROM Walmart
group by 1,2
) as tbl
where rnk = 1;


-- Q.3 Identify the busiest day for each branch based on the nmber of transactions 
select * from(
select
	branch,
	dayname(STR_TO_DATE(date, '%d/%m/%y')) AS day_name,
	count(*) as no_transactions,
    RANK() OVER (PARTITION BY branch order by count(*) desc) as Rnk 
from Walmart
group by 1, 2) as t
where rnk = 1;

-- Q.4 Calculate the total quantity of items sold per payment method.list payment method and total quantity.
 select 
	payment_method,
    sum(quantity) as no_quantity_sold
 from Walmart
 group by payment_method;
 
-- Q.5 determine the avg, min,max,rating of products or each city
select city,
	avg(rating) as avg_rating,
    min(rating) as min_rating,
    max(rating) as max_rating
from walmart
group by city 
order by 4 desc;
    
-- Q.6 calculate the total profit for each category by considering total profit 
select category,
	sum(total) as total_revenue,
	sum(total*profit_margin) as profit
from Walmart
group by 1;

-- Q.7 Determine the most common payment for each branch.display branch nd the preferred payment method;
WITH cte
as
(select 
	branch,
    payment_method,
    count(*) as total_trans,
    RANK() over (partition by branch order by count(*) desc) as rnk
from Walmart
group by 1,2
) 
select * from cte where rnk = 1;

-- Q.8 Categorise sales into 3 group MORNING, AFTERNOON, EVENING. Find out each of the shift and number of invoices
SELECT branch,
CASE
    WHEN EXTRACT(HOUR FROM CAST(time AS TIME)) < 12 THEN 'Morning'
    WHEN EXTRACT(HOUR FROM CAST(time AS TIME)) BETWEEN 12 AND 17 THEN 'Afternoon'
    ELSE 'Evening'
END AS day_time,
COUNT(*)
FROM walmart
GROUP BY 1,2
order by 1,3 desc;	 

-- Q.9 Identify 5 branch with highest decrease ratio in revenue compare to last year(current year 2023 and last year 2022)
 
 with revenue_2022 as 
	 (select branch,
		sum(total) as revenue
	from walmart
	WHERE extract(YEAR FROM STR_TO_DATE(date, '%d/%m/%y')) = 2022
	group by 1
		),
revenue_2023 as 
(select branch,
		sum(total) as revenue
from walmart
WHERE extract(YEAR FROM STR_TO_DATE(date, '%d/%m/%y')) = 2023
group by 1
		)
select 
	ls.branch,
    ls.revenue as last_year_revenue,
    cs.revenue as current_year_revenue,
    round(
		(ls.revenue - cs.revenue) / ls.revenue* 100 ,2
        ) as decreased_revenue_ratio
from revenue_2022 as ls
Join revenue_2023 as cs
on ls.branch = cs.branch
where ls.revenue > cs.revenue
order by 4 desc
limit 5;

-- Q.10 orderby hour having the maximum transactions?
SELECT 
EXTRACT(HOUR FROM CAST(time AS TIME)) AS hour,
COUNT(*) AS transactions
FROM walmart
GROUP BY hour
ORDER BY transactions DESC;

-- Q.11 Find Top 3 Cities by Revenue
SELECT city,
       SUM(total) AS revenue
FROM walmart
GROUP BY city
ORDER BY revenue DESC
LIMIT 3;

-- Q.12 Find Category Revenue Contribution (%)
SELECT 
    category,
    SUM(total) AS revenue,
    ROUND(100 * SUM(total) / (SELECT SUM(total) FROM walmart),2) AS revenue_percentage
FROM walmart
GROUP BY category
ORDER BY revenue DESC;

-- Q.13 Find Branch Revenue Ranking
SELECT 
    branch,
    SUM(total) AS revenue,
    RANK() OVER(ORDER BY SUM(total) DESC) AS revenue_rank
FROM walmart
GROUP BY branch;

-- Q.14 Find Average Revenue Per Transaction by Branch
SELECT 
    branch,
    AVG(total) AS avg_revenue_per_transaction
FROM walmart
GROUP BY branch
ORDER BY avg_revenue_per_transaction DESC;

-- Q.15. Find Top Category by Quantity Sold in Each City
SELECT *
FROM(
SELECT 
    city,
    category,
    SUM(quantity) AS total_quantity,
    RANK() OVER(PARTITION BY city ORDER BY SUM(quantity) DESC) AS rnk
FROM walmart
GROUP BY city, category
) t
WHERE rnk = 1;

-- Q.17. Find Profit Generated by Each Branch
SELECT 
    branch,
    SUM(total * profit_margin) AS total_profit
FROM walmart
GROUP BY branch
ORDER BY total_profit DESC;

-- Q. 18 Find Daily Revenue Trend
SELECT 
    STR_TO_DATE(date,'%d/%m/%y') AS sales_date,
    SUM(total) AS revenue
FROM walmart
GROUP BY sales_date
ORDER BY sales_date;

-- Q.19 Identify Low Performing Categories (Below Average Revenue)
SELECT 
    category,
    SUM(total) AS revenue
FROM walmart
GROUP BY category
HAVING SUM(total) < (
        SELECT AVG(category_revenue)
        FROM(
            SELECT SUM(total) AS category_revenue
            FROM walmart
            GROUP BY category
        ) t
);

-- Q.20 Find Top Transaction in Each City
SELECT *
FROM(
SELECT 
    city,
    invoice_id,
    total,
    RANK() OVER(PARTITION BY city ORDER BY total DESC) AS rnk
FROM walmart
) t
WHERE rnk = 1;

-- Q.21  Find the Month With Highest Revenue
SELECT 
    MONTH(STR_TO_DATE(date,'%d/%m/%y')) AS month,
    SUM(total) AS revenue
FROM walmart
GROUP BY month
ORDER BY revenue DESC
LIMIT 1;

-- Q.22 Find Average Quantity Sold per Category
SELECT 
    category,
    AVG(quantity) AS avg_quantity
FROM walmart
GROUP BY category
ORDER BY avg_quantity DESC;

-- Q.23 Find the Branch With Highest Number of Transactions
SELECT 
    branch,
    COUNT(*) AS transactions
FROM walmart
GROUP BY branch
ORDER BY transactions DESC
LIMIT 1;

-- Q.24 Find Top 3 Cities by Total Quantity Sold
SELECT 
    city,
    SUM(quantity) AS total_quantity
FROM walmart
GROUP BY city
ORDER BY total_quantity DESC
LIMIT 3;

-- Q.25 Find Revenue Generated per Day of Week
SELECT 
    DAYNAME(STR_TO_DATE(date,'%d/%m/%y')) AS day_name,
    SUM(total) AS revenue
FROM walmart
GROUP BY day_name
ORDER BY revenue DESC;

-- Q.26 Find Average Revenue Generated per City
SELECT 
    city,
    AVG(total) AS avg_revenue
FROM walmart
GROUP BY city
ORDER BY avg_revenue DESC;
